const hrefPath = "categories-defs.svg";
export const categories = [
  {
    id: "Family",
    svgId: "icon-pencil2",
    href: `${hrefPath}#icon-pencil2`,
    name: "Family",
  },
  {
    id: "Paint",
    svgId: "icon-paint-format",
    href: `${hrefPath}#icon-paint-format`,
    name: "Paint",
  },
  {
    id: "Media",
    svgId: "icon-image",
    href: `${hrefPath}#icon-image`,
    name: "Media",
  },
  {
    id: "Headset",
    svgId: "icon-headphones",
    href: `${hrefPath}#icon-headphones`,
    name: "Headset",
  },
  {
    id: "Books",
    svgId: "icon-book",
    href: `${hrefPath}#icon-book`,
    name: "Books",
  },
  {
    id: "Work",
    svgId: "icon-profile",
    href: `${hrefPath}#icon-profile`,
    name: "Work",
  },
  {
    id: "PC",
    svgId: "icon-display",
    href: `${hrefPath}#icon-display`,
    name: "PC",
  },
  {
    id: "Phones",
    svgId: "icon-mobile",
    href: `${hrefPath}#icon-mobile`,
    name: "Phones",
  },
  {
    id: "TV",
    svgId: "icon-tv",
    href: `${hrefPath}#icon-tv`,
    name: "TV",
  },
  {
    id: "Tools",
    svgId: "icon-wrench",
    href: `${hrefPath}#icon-wrench`,
    name: "Tools",
  },
  {
    id: "Medicine",
    svgId: "icon-aid-kit",
    href: `${hrefPath}#icon-aid-kit`,
    name: "Medicine",
  },
  {
    id: "Cutlery",
    svgId: "icon-spoon-knife",
    href: `${hrefPath}#icon-spoon-knife`,
    name: "Cutlery",
  },
  {
    id: "Garden",
    svgId: "icon-leaf",
    href: `${hrefPath}#icon-leaf`,
    name: "Garden",
  },
  {
    id: "Fuel",
    svgId: "icon-fire",
    href: `${hrefPath}#icon-fire`,
    name: "Fuel",
  },
  {
    id: "Vehicles",
    svgId: "icon-truck",
    href: `${hrefPath}#icon-truck`,
    name: "Vehicles",
  },
  {
    id: "Toys",
    svgId: "icon-reddit",
    href: `${hrefPath}#icon-reddit`,
    name: "Toys",
  },
];
export const cities = [
  "Kyiv",
  "Kharkiv",
  "Odesa",
  "Dnipro",
  "Lviv",
  "Kryvyi Rih",
  "Mykolaiv",
  "Mariupol",
  "Sevastopol",
  "Luhansk",
  "Vinnytsia",
  "Zaporizhzhia",
  "Simferopol",
  "Kherson",
  "Poltava",
  "Chernihiv",
  "Cherkasy",
  "Zhytomyr",
  "Sumy",
  "Rivne",
  "Ivano-Frankivsk",
  "Ternopil",
  "Chernivtsi",
  "Lutsk",
  "Kropyvnytskyi",
  "Uzhhorod",
  "Khmelnytskyi",
  "Kremenchuk",
  "Bila Tserkva",
  "Melitopol",
  "Nikopol",
  "Sloviansk",
  "Brovary",
  "Berdiansk",
  "Pavlohrad",
  "Kamianets-Podilskyi",
  "Alchevsk",
  "Yevpatoria",
  "Konotop",
  "Uman",
  "Shostka",
  "Oleksandriia",
  "Mukachevo",
  "Kostopil",
  "Netishyn",
  "Enerhodar",
  "Horlivka",
  "Kadiivka",
  "Druzhkivka",
  "Lysychansk",
  "Rubizhne",
  "Bakhmut",
  "Kramatorsk",
  "Pokrovsk",
  "Sieverodonetsk",
  "Toretsk",
  "Dniprorudne",
  "Nova Kakhovka",
  "Pryluky",
  "Smila",
  "Fastiv",
  "Obukhiv",
  "Yalta",
  "Boryspil",
  "Irpin",
  "Boyarka",
  "Vyshneve",
  "Chornobyl",
  "Slavutych",
  "Borodianka",
  "Vyshhorod",
  "Vasylkiv",
  "Bilhorod-Dnistrovskyi",
  "Yuzhne",
  "Izmail",
  "Chornomorsk",
  "Reni",
  "Berezan",
  "Boryslav",
  "Drohobych",
  "Stryi",
  "Truskavets",
  "Novovolynsk",
  "Chervonohrad",
  "Volodymyr",
  "Drohobych",
  "Zhovkva",
  "Zhytomyr",
  "Zolochiv",
  "Zvenyhorodka",
];
